# Libraries Definition


In [14]:
import pandas as pd
import numpy as np
import matplotlib as pt
import seaborn as sns 
from sklearn.model_selection import train_test_split

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import svm
from sklearn import linear_model

#model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn import tree
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier

from math import sqrt


cmap = sns.cubehelix_palette(dark=.3, light=.8, as_cmap=True)
%matplotlib inline
pt.style.use('ggplot')

# Data Preparation 

In [2]:
data = pd.read_csv("defaultcreditcardclients.csv") 

In [3]:
#Check Null Values
print("No. of columns containing null values")
print(len(data.columns[data.isna().any()]))

No. of columns containing null values
0


In [4]:
data.rename(columns={'default payment next month': 'IsDefault'}, inplace=True)
#Drop ID column since it is not required for prediction or analysis
data.drop('ID', axis=1, inplace=True)
#Transformar variable dependiente de Integer a Bool
data['_IsDefault']=True
data.info()
data['_IsDefault']=data['IsDefault'].astype(bool)
data.drop('IsDefault', axis=1, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
LIMIT_BAL     30000 non-null int64
SEX           30000 non-null int64
EDUCATION     30000 non-null int64
MARRIAGE      30000 non-null int64
AGE           30000 non-null int64
PAY_0         30000 non-null int64
PAY_2         30000 non-null int64
PAY_3         30000 non-null int64
PAY_4         30000 non-null int64
PAY_5         30000 non-null int64
PAY_6         30000 non-null int64
BILL_AMT1     30000 non-null int64
BILL_AMT2     30000 non-null int64
BILL_AMT3     30000 non-null int64
BILL_AMT4     30000 non-null int64
BILL_AMT5     30000 non-null int64
BILL_AMT6     30000 non-null int64
PAY_AMT1      30000 non-null int64
PAY_AMT2      30000 non-null int64
PAY_AMT3      30000 non-null int64
PAY_AMT4      30000 non-null int64
PAY_AMT5      30000 non-null int64
PAY_AMT6      30000 non-null int64
IsDefault     30000 non-null int64
_IsDefault    30000 non-null bool
dtypes: bool(1), 

In [5]:
data.rename(columns={'_IsDefault': 'IsDefault'}, inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
LIMIT_BAL    30000 non-null int64
SEX          30000 non-null int64
EDUCATION    30000 non-null int64
MARRIAGE     30000 non-null int64
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
PAY_3        30000 non-null int64
PAY_4        30000 non-null int64
PAY_5        30000 non-null int64
PAY_6        30000 non-null int64
BILL_AMT1    30000 non-null int64
BILL_AMT2    30000 non-null int64
BILL_AMT3    30000 non-null int64
BILL_AMT4    30000 non-null int64
BILL_AMT5    30000 non-null int64
BILL_AMT6    30000 non-null int64
PAY_AMT1     30000 non-null int64
PAY_AMT2     30000 non-null int64
PAY_AMT3     30000 non-null int64
PAY_AMT4     30000 non-null int64
PAY_AMT5     30000 non-null int64
PAY_AMT6     30000 non-null int64
IsDefault    30000 non-null bool
dtypes: bool(1), int64(23)
memory usage: 5.3 MB


# CoVariance

In [ ]:
covMatrix = np.cov(data,bias=True)
#sn.heatmap(covMatrix, annot=True, fmt='g')

# Feature Engineering

In [ ]:
#RFE
x = data.iloc[:,0:23]
y= data.iloc[:,23]

model = RandomForestClassifier(n_estimators=20, random_state=0)
rfe = RFE(model, 3)
fit = rfe.fit(x, y)
rfe = RFE(modelRF, 3)
fit = rfe.fit(x, y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)


In [ ]:
#PCA
# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(x)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

In [ ]:
# ExtraTreesClassifer
model = ExtraTreesClassifier(n_estimators=10)
model.fit(x, y)
print(model.feature_importances_)

# Create RFE Dataset

In [26]:
columns = ['AGE', 'PAY_0','PAY_2','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6','IsDefault']
dataRFE = pd.DataFrame(data, columns=columns)

dataRFE['_Age']=np.log(dataRFE['AGE'])
dataRFE['_Bill1']=np.log(dataRFE['BILL_AMT1'])
dataRFE['_Bill2']=np.log(dataRFE['BILL_AMT2'])
dataRFE['_Bill3']=np.log(dataRFE['BILL_AMT3'])
dataRFE['_Bill4']=np.log(dataRFE['BILL_AMT4'])
dataRFE['_Bill5']=np.log(dataRFE['BILL_AMT5'])
dataRFE['_Bill6']=np.log(dataRFE['BILL_AMT6'])

/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """
/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """
/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  
/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in log
  
/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys
/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in log
  import sys
/home/jorge/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
/home/jorge/anacon

In [22]:
dataRFE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
BILL_AMT1    30000 non-null int64
BILL_AMT2    30000 non-null int64
BILL_AMT3    30000 non-null int64
BILL_AMT4    30000 non-null int64
BILL_AMT5    30000 non-null int64
BILL_AMT6    30000 non-null int64
IsDefault    30000 non-null bool
_Age         30000 non-null float64
dtypes: bool(1), float64(1), int64(9)
memory usage: 2.3 MB


In [51]:
#Check Null Values
print("No. of columns containing null values")
print(len(dataRFE.columns[dataRFE.isna().any()]))


No. of columns containing null values
6


In [52]:
dataRFE.dropna(inplace=True)

In [37]:
dataRFE.drop('AGE', axis=1, inplace=True)
dataRFE.drop('BILL_AMT1', axis=1, inplace=True)
dataRFE.drop('BILL_AMT2', axis=1, inplace=True)
dataRFE.drop('BILL_AMT3', axis=1, inplace=True)
dataRFE.drop('BILL_AMT4', axis=1, inplace=True)
dataRFE.drop('BILL_AMT5', axis=1, inplace=True)
dataRFE.drop('BILL_AMT6', axis=1, inplace=True)

In [49]:
dataRFE.replace([np.inf, -np.inf], np.nan,inplace=True)

In [53]:
dataRFE.head()

PAY_0  PAY_2  IsDefault      _Age     _Bill1     _Bill2     _Bill3  \
1     -1      2       True  3.258097   7.894318   7.452982   7.894318   
2      0      0      False  3.526361  10.283259   9.548739   9.514806   
3      0      0      False  3.610918  10.757690  10.783799  10.805497   
4     -1      0      False  4.043051   9.061492   8.642944  10.486680   
5      0      0      False  3.610918  11.072869  10.952016  10.961417   

      _Bill4     _Bill5     _Bill6  
1   8.093157   8.147578   8.089789  
2   9.570180   9.612333   9.651752  
3  10.251112  10.273636  10.293737  
4   9.949416   9.859849   9.859065  
5   9.872719   9.884254   9.904687

# Define Datasets

In [54]:
#features
features = dataRFE.iloc[:,0:10]
features.head()

PAY_0  PAY_2  IsDefault      _Age     _Bill1     _Bill2     _Bill3  \
1     -1      2       True  3.258097   7.894318   7.452982   7.894318   
2      0      0      False  3.526361  10.283259   9.548739   9.514806   
3      0      0      False  3.610918  10.757690  10.783799  10.805497   
4     -1      0      False  4.043051   9.061492   8.642944  10.486680   
5      0      0      False  3.610918  11.072869  10.952016  10.961417   

      _Bill4     _Bill5     _Bill6  
1   8.093157   8.147578   8.089789  
2   9.570180   9.612333   9.651752  
3  10.251112  10.273636  10.293737  
4   9.949416   9.859849   9.859065  
5   9.872719   9.884254   9.904687

In [55]:
#dependent variable
depVar = dataRFE['IsDefault']
depVar.head()

1     True
2    False
3    False
4    False
5    False
Name: IsDefault, dtype: bool

In [56]:
features_train, features_test, depVar_train, depVar_test = train_test_split(features, depVar, test_size=0.3, random_state=0)

In [57]:
features_train.shape, features_test.shape

((15668, 10), (6716, 10))

# Clasification-Model Training

Random Forest Run1(20 estimators,max_depth=8)

In [ ]:
forest = RandomForestClassifier(random_state = 1)
n_estimators = [20,100, 300, 500, 800, 1200]
max_depth = [5, 8, 15,16, 25, 30,32]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10] 

hyperF = dict(n_estimators = n_estimators, max_depth = max_depth,  
              min_samples_split = min_samples_split, 
             min_samples_leaf = min_samples_leaf)

gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, 
                      n_jobs = -1)
gridF = gridF.fit(features_train, depVar_train)
print(gridF.best_params_)

In [ ]:
modelRF = RandomForestClassifier(n_estimators=20, random_state=0,max_depth=8)
modelRF.fit(features_train, depVar_train)
modelRF_pred = modelRF.predict(features_test)
modelRF.score(features_train, depVar_train)
print(cross_val_score(modelRF, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelRF_pred))
print(classification_report(depVar_test,modelRF_pred))
print(accuracy_score(depVar_test, modelRF_pred))

#Accuracy result 0.8247777777777778

Random Forest Run2(100 estimators,max_depth=8)

In [58]:
modelRF = RandomForestClassifier(n_estimators=100, random_state=0,max_depth=16)
modelRF.fit(features_train, depVar_train)
modelRF_pred = modelRF.predict(features_test)
modelRF.score(features_train, depVar_train)
print(cross_val_score(modelRF, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelRF_pred))
print(classification_report(depVar_test,modelRF_pred))
print(accuracy_score(depVar_test, modelRF_pred))

#Accuracy result 0.8256666666666667

[1. 1. 1. 1. 1.]
[[5178    0]
 [   0 1538]]
              precision    recall  f1-score   support

       False       1.00      1.00      1.00      5178
        True       1.00      1.00      1.00      1538

    accuracy                           1.00      6716
   macro avg       1.00      1.00      1.00      6716
weighted avg       1.00      1.00      1.00      6716

1.0


Random Forest Run3(200 estimators,max_depth=16)

In [ ]:
modelRF = RandomForestClassifier(n_estimators=200, random_state=0,max_depth=8)
modelRF.fit(features_train, depVar_train)
modelRF_pred = modelRF.predict(features_test)
modelRF.score(features_train, depVar_train)
print(cross_val_score(modelRF, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelRF_pred))
print(classification_report(depVar_test,modelRF_pred))
print(accuracy_score(depVar_test, modelRF_pred))

#Accuracy result 0.8256666666666667

Support Vector Machine Run1

In [ ]:
#Buscando mejores parametros

In [ ]:
from sklearn.model_selection import GridSearchCV
def svc_param_selection(X, y, nfolds):
    Cs = [0.001, 0.01, 0.1, 1, 10]
    gammas = [0.001, 0.01, 0.1, 1]
    param_grid = {'C': Cs, 'gamma' : gammas}
    grid_search = GridSearchCV(svm.SVC(kernel='rbf'), param_grid, cv=nfolds)
    grid_search.fit(X,y)
    grid_search.best_params_
    return grid_search.best_params_

grid=svc_param_selection(features_train,depVar_train,10)
#Mejores parametros
{'C': 10, 'gamma': 0.001}



In [ ]:
print(grid)

In [16]:
from sklearn.svm import SVC
modelSVM = SVC(C=10,gamma=0.001,kernel='rbf')
modelSVM.fit(features_train, depVar_train)
modelSVM_pred = modelSVM.predict(features_test)
modelSVM.score(features_train, depVar_train)
print(cross_val_score(modelSVM, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelSVM_pred))
print(classification_report(depVar_test,modelSVM_pred))
print(accuracy_score(depVar_test, modelSVM_pred))

#Accuracy result 0.7857777777777778

[0.78952381 0.78547619 0.78595238 0.78571429 0.79190476]
[[7027   33]
 [1780  160]]
              precision    recall  f1-score   support

       False       0.80      1.00      0.89      7060
        True       0.83      0.08      0.15      1940

    accuracy                           0.80      9000
   macro avg       0.81      0.54      0.52      9000
weighted avg       0.80      0.80      0.73      9000

0.7985555555555556


AdaBoost Run1

In [ ]:
#Encontrando mejores parametros
from sklearn.model_selection import KFold
crossvalidation=KFold(n_splits=10,shuffle=True,random_state=1)
for depth in range (1,10):
    tree_classifier=tree.DecisionTreeClassifier(max_depth=depth,random_state=1)
    if tree_classifier.fit(features_train,depVar_train).tree_.max_depth<depth:
        break
    score=np.mean(cross_val_score(tree_classifier,features_train,depVar_train,scoring='accuracy', cv=crossvalidation,n_jobs=1))
    print(depth, score)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
ada=AdaBoostClassifier()
search_grid={'n_estimators':[50,500,1000,2000],'learning_rate':[.001,0.01,.1,1]}
search=GridSearchCV(estimator=ada,param_grid=search_grid,scoring='accuracy',n_jobs=1,cv=crossvalidation)

In [ ]:
search.fit(features_train,depVar_train)
print(search.best_params_)
print(search.best_score_)

In [17]:
from sklearn.ensemble import AdaBoostClassifier
modelABC = AdaBoostClassifier(n_estimators=50,learning_rate=0.001)
modelABC.fit(features_train, depVar_train)
modelABC_pred = modelABC.predict(features_test)
modelABC.score(features_train, depVar_train)
print(cross_val_score(modelABC, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelABC_pred))
print(classification_report(depVar_test,modelABC_pred))
print(accuracy_score(depVar_test, modelABC_pred))

#Accuracy result 0.826

[1. 1. 1. 1. 1.]
[[7060    0]
 [   0 1940]]
              precision    recall  f1-score   support

       False       1.00      1.00      1.00      7060
        True       1.00      1.00      1.00      1940

    accuracy                           1.00      9000
   macro avg       1.00      1.00      1.00      9000
weighted avg       1.00      1.00      1.00      9000

1.0
