# Libraries Definition


In [12]:
import pandas as pd
import numpy as np
import matplotlib as pt
import seaborn as sns 
from sklearn.model_selection import train_test_split

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import svm
from sklearn import linear_model

#model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn import tree
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier

from math import sqrt


cmap = sns.cubehelix_palette(dark=.3, light=.8, as_cmap=True)
%matplotlib inline
pt.style.use('ggplot')

# Data Preparation 

In [2]:
data = pd.read_csv("defaultcreditcardclients.csv") 

In [3]:
#Check Null Values
print("No. of columns containing null values")
print(len(data.columns[data.isna().any()]))

No. of columns containing null values
0


In [4]:
data.rename(columns={'default payment next month': 'IsDefault'}, inplace=True)
#Drop ID column since it is not required for prediction or analysis
data.drop('ID', axis=1, inplace=True)
#Transformar variable dependiente de Integer a Bool
data['_IsDefault']=True
data.info()
data['_IsDefault']=data['IsDefault'].astype(bool)
data.drop('IsDefault', axis=1, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
LIMIT_BAL     30000 non-null int64
SEX           30000 non-null int64
EDUCATION     30000 non-null int64
MARRIAGE      30000 non-null int64
AGE           30000 non-null int64
PAY_0         30000 non-null int64
PAY_2         30000 non-null int64
PAY_3         30000 non-null int64
PAY_4         30000 non-null int64
PAY_5         30000 non-null int64
PAY_6         30000 non-null int64
BILL_AMT1     30000 non-null int64
BILL_AMT2     30000 non-null int64
BILL_AMT3     30000 non-null int64
BILL_AMT4     30000 non-null int64
BILL_AMT5     30000 non-null int64
BILL_AMT6     30000 non-null int64
PAY_AMT1      30000 non-null int64
PAY_AMT2      30000 non-null int64
PAY_AMT3      30000 non-null int64
PAY_AMT4      30000 non-null int64
PAY_AMT5      30000 non-null int64
PAY_AMT6      30000 non-null int64
IsDefault     30000 non-null int64
_IsDefault    30000 non-null bool
dtypes: bool(1), 

In [5]:
data.rename(columns={'_IsDefault': 'IsDefault'}, inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
LIMIT_BAL    30000 non-null int64
SEX          30000 non-null int64
EDUCATION    30000 non-null int64
MARRIAGE     30000 non-null int64
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
PAY_3        30000 non-null int64
PAY_4        30000 non-null int64
PAY_5        30000 non-null int64
PAY_6        30000 non-null int64
BILL_AMT1    30000 non-null int64
BILL_AMT2    30000 non-null int64
BILL_AMT3    30000 non-null int64
BILL_AMT4    30000 non-null int64
BILL_AMT5    30000 non-null int64
BILL_AMT6    30000 non-null int64
PAY_AMT1     30000 non-null int64
PAY_AMT2     30000 non-null int64
PAY_AMT3     30000 non-null int64
PAY_AMT4     30000 non-null int64
PAY_AMT5     30000 non-null int64
PAY_AMT6     30000 non-null int64
IsDefault    30000 non-null bool
dtypes: bool(1), int64(23)
memory usage: 5.3 MB


# CoVariance

In [ ]:
covMatrix = np.cov(data,bias=True)
#sn.heatmap(covMatrix, annot=True, fmt='g')

# Feature Engineering

In [ ]:
#RFE
x = data.iloc[:,0:23]
y= data.iloc[:,23]

model = RandomForestClassifier(n_estimators=20, random_state=0)
rfe = RFE(model, 3)
fit = rfe.fit(x, y)
rfe = RFE(modelRF, 3)
fit = rfe.fit(x, y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)


In [ ]:
#PCA
# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(x)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

In [ ]:
# ExtraTreesClassifer
model = ExtraTreesClassifier(n_estimators=10)
model.fit(x, y)
print(model.feature_importances_)

# Create RFE Dataset

In [ ]:
columns = ['AGE', 'PAY_0','PAY_2','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6','IsDefault']
dataRFE = pd.DataFrame(data, columns=columns)

In [ ]:
dataRFE.info()

# Define Datasets

In [7]:
#features
features = data.iloc[:,0:23]
features.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -2  ...        689          0          0          0         0       689   
1      0  ...       2682       3272       3455       3261         0      1000   
2      0  ...      13559      14331      14948      15549      1518      1500   
3      0  ...      49291      28314      28959      29547      2000      2019   
4      0  ...      35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0         0         0         0  
1      1000      1000         0      2000  
2      1000      1000      1000      5000  
3      1200      1100      1069      1000  
4     10000      9000       689       679  

[5 rows x 23 columns]

In [8]:
#dependent variable
depVar = data['IsDefault']
depVar.head()

0     True
1     True
2    False
3    False
4    False
Name: IsDefault, dtype: bool

In [9]:
features_train, features_test, depVar_train, depVar_test = train_test_split(features, depVar, test_size=0.3, random_state=0)

In [10]:
features_train.shape, features_test.shape

((21000, 23), (9000, 23))

# Clasification-Model Training

Esta funcion ayuda a encontrar el mejor conjunto de parametros,pero consume muchos recursos

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(random_state = 1)
n_estimators = [20,100, 300, 500, 800, 1200]
max_depth = [5, 8, 15,16, 25, 30,32]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10] 

hyperF = dict(n_estimators = n_estimators, max_depth = max_depth,  
              min_samples_split = min_samples_split, 
             min_samples_leaf = min_samples_leaf)

gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, 
                      n_jobs = -1)
gridF = gridF.fit(features_train, depVar_train)
print(gridF.best_params_)

Fitting 3 folds for each of 840 candidates, totalling 2520 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed: 11.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed: 29.3min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed: 72.0min


In [ ]:
Random Forest 20 estimators,max_depth=8

In [11]:
modelRF = RandomForestClassifier(n_estimators=20, random_state=0,max_depth=8)
modelRF.fit(features_train, depVar_train)
modelRF_pred = modelRF.predict(features_test)
modelRF.score(features_train, depVar_train)
print(cross_val_score(modelRF, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelRF_pred))
print(classification_report(depVar_test,modelRF_pred))
print(accuracy_score(depVar_test, modelRF_pred))

#Accuracy result 0.8247777777777778

[0.82       0.81952381 0.81261905 0.81357143 0.8152381 ]
[[6747  313]
 [1264  676]]
              precision    recall  f1-score   support

       False       0.84      0.96      0.90      7060
        True       0.68      0.35      0.46      1940

    accuracy                           0.82      9000
   macro avg       0.76      0.65      0.68      9000
weighted avg       0.81      0.82      0.80      9000

0.8247777777777778


Random Forest Run2(100 estimators,max_depth=8)

In [12]:
modelRF = RandomForestClassifier(n_estimators=100, random_state=0,max_depth=8)
modelRF.fit(features_train, depVar_train)
modelRF_pred = modelRF.predict(features_test)
modelRF.score(features_train, depVar_train)
print(cross_val_score(modelRF, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelRF_pred))
print(classification_report(depVar_test,modelRF_pred))
print(accuracy_score(depVar_test, modelRF_pred))

#Accuracy result 0.8256666666666667

[0.82071429 0.82238095 0.81357143 0.81309524 0.81619048]
[[6744  316]
 [1253  687]]
              precision    recall  f1-score   support

       False       0.84      0.96      0.90      7060
        True       0.68      0.35      0.47      1940

    accuracy                           0.83      9000
   macro avg       0.76      0.65      0.68      9000
weighted avg       0.81      0.83      0.80      9000

0.8256666666666667


In [25]:
dat=depVar_test.copy()

In [28]:
dat1=dat.to_frame()

In [30]:
dat1

IsDefault
8225       False
10794      False
9163       False
26591      False
6631       False
14161       True
252         True
2566       False
3478       False
2917       False
12775      False
29010      False
7983       False
21976      False
21139      False
12477      False
3199        True
9708       False
7631       False
6937       False
6175       False
16560      False
14733       True
19277      False
16290       True
19552       True
1482       False
24743      False
19704      False
4273        True
...          ...
4504       False
16348      False
2610       False
2074       False
7342       False
25187      False
24853      False
23225       True
2280       False
20827      False
25691       True
5705        True
7553       False
12063      False
11607      False
22038      False
26598       True
14600      False
20945      False
1310        True
28352      False
23682      False
21383      False
675         True
21313      False
21914      False
17453      False
20344      False
1878       False
6465       False

[9000 rows x 1 columns]

In [31]:
dat1.groupby('IsDefault').count()
dat1['IsDefault'].value_counts()

False    7060
True     1940
Name: IsDefault, dtype: int64

Random Forest Run3(200 estimators,max_depth=16)

In [13]:
modelRF = RandomForestClassifier(n_estimators=200, random_state=0,max_depth=16)
modelRF.fit(features_train, depVar_train)
modelRF_pred = modelRF.predict(features_test)
modelRF.score(features_train, depVar_train)
print(cross_val_score(modelRF, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelRF_pred))
print(classification_report(depVar_test,modelRF_pred))
print(accuracy_score(depVar_test, modelRF_pred))

#Accuracy result 0.8256666666666667

[0.82261905 0.82238095 0.815      0.81214286 0.81833333]
[[6714  346]
 [1257  683]]
              precision    recall  f1-score   support

       False       0.84      0.95      0.89      7060
        True       0.66      0.35      0.46      1940

    accuracy                           0.82      9000
   macro avg       0.75      0.65      0.68      9000
weighted avg       0.80      0.82      0.80      9000

0.8218888888888889


Support Vector Machine Run1

In [ ]:
#Buscando mejores parametros

In [11]:
from sklearn.model_selection import GridSearchCV
def svc_param_selection(X, y, nfolds):
    Cs = [0.001, 0.01, 0.1, 1, 10]
    gammas = [0.001, 0.01, 0.1, 1]
    param_grid = {'C': Cs, 'gamma' : gammas}
    grid_search = GridSearchCV(svm.SVC(kernel='rbf'), param_grid, cv=nfolds)
    grid_search.fit(X,y)
    grid_search.best_params_
    return grid_search.best_params_

grid=svc_param_selection(features_train,depVar_train,10)
#Mejores parametros
{'C': 10, 'gamma': 0.001}



In [12]:
print(grid)

{'C': 10, 'gamma': 0.001}


In [13]:
from sklearn.svm import SVC
modelSVM = SVC(C=10,gamma=0.001,kernel='rbf')
modelSVM.fit(features_train, depVar_train)
modelSVM_pred = modelSVM.predict(features_test)
modelSVM.score(features_train, depVar_train)
print(cross_val_score(modelSVM, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelSVM_pred))
print(classification_report(depVar_test,modelSVM_pred))
print(accuracy_score(depVar_test, modelSVM_pred))

#Accuracy result 0.7857777777777778

[0.77809524 0.77666667 0.77880952 0.77857143 0.7802381 ]
[[7015   45]
 [1883   57]]
              precision    recall  f1-score   support

       False       0.79      0.99      0.88      7060
        True       0.56      0.03      0.06      1940

    accuracy                           0.79      9000
   macro avg       0.67      0.51      0.47      9000
weighted avg       0.74      0.79      0.70      9000

0.7857777777777778


AdaBoost Run1

In [13]:
#Encontrando mejores parametros
from sklearn.model_selection import KFold
crossvalidation=KFold(n_splits=10,shuffle=True,random_state=1)
for depth in range (1,10):
    tree_classifier=tree.DecisionTreeClassifier(max_depth=depth,random_state=1)
    if tree_classifier.fit(features_train,depVar_train).tree_.max_depth<depth:
        break
    score=np.mean(cross_val_score(tree_classifier,features_train,depVar_train,scoring='accuracy', cv=crossvalidation,n_jobs=1))
    print(depth, score)

1 0.816857142857143
2 0.816857142857143
3 0.8181428571428571
4 0.8163809523809524
5 0.8163333333333334
6 0.8146190476190476
7 0.8142857142857143
8 0.8116190476190477
9 0.8084761904761905


In [19]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
ada=AdaBoostClassifier()
search_grid={'n_estimators':[50,500,1000,2000],'learning_rate':[.001,0.01,.1,1]}
search=GridSearchCV(estimator=ada,param_grid=search_grid,scoring='accuracy',n_jobs=1,cv=crossvalidation)

In [20]:
search.fit(features_train,depVar_train)
print(search.best_params_)
print(search.best_score_)

{'learning_rate': 0.001, 'n_estimators': 50}
0.816857142857143


In [21]:
from sklearn.ensemble import AdaBoostClassifier
modelABC = AdaBoostClassifier(n_estimators=50,learning_rate=0.001)
modelABC.fit(features_train, depVar_train)
modelABC_pred = modelABC.predict(features_test)
modelABC.score(features_train, depVar_train)
print(cross_val_score(modelABC, features_train, depVar_train)) 
print(confusion_matrix(depVar_test,modelABC_pred))
print(classification_report(depVar_test,modelABC_pred))
print(accuracy_score(depVar_test, modelABC_pred))

#Accuracy result 0.826

[0.81761905 0.82333333 0.81738095 0.81214286 0.81380952]
[[6791  269]
 [1297  643]]
              precision    recall  f1-score   support

       False       0.84      0.96      0.90      7060
        True       0.71      0.33      0.45      1940

    accuracy                           0.83      9000
   macro avg       0.77      0.65      0.67      9000
weighted avg       0.81      0.83      0.80      9000

0.826
